# Generated by Django 5.0.6 on 2024-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_evenement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
