# Generated by Django 5.0.6 on 2024-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_type_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
